### ISSUE TITLE
Boundaries, intesi come perimetro di una zona della scena

### ISSUE THREAD

**Issue by a55mage** [cg3hci/ECARules4All#2]
Attualmente è possibile creare una regola di questo tipo

when the human visitor teleports to scene Artwork1 then 
the robot Artist startsAnimation artwork1Presentation

Non sono sicuro che per "scene" si intenda una zona di un livello piuttosto che l'intero livello.
Se anche fosse una zona di un livello, non mi è però possibile creare una regola del tipo

when the human visitor teleports **out** of scene Artwork1 then 
the robot Artist startsAnimation artwork1Presentation

Questa è una funzione secondo me molto importante ed è piuttosto semplice da gestire con i trigger collider di unity

**Comment by davidespano** [comment]
Per il resto ci sono i trigger.
